version: "3.1"

services:
  s_jenkins:
    container_name: c_jenkins
    image: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/app_data/jenkins:/var/jenkins_home
